### PR TITLE
Update univColor.js

### PR DESCRIPTION
**Pull request by Kwoneunhye**
color correction

### CODE REVIEW

**Comment by nayunhwan** [comment]
Can you show me that why '#01499a' is the primary color of INU?
I had searched about that the primary color was '#0C3689'.

**Comment by Kwoneunhye** [comment]
First of all, I am sorry to write another color code. 
The color of our school is 1 73 154 with RGB code. 
When converting this data into HTML color code, I can obtain a value of # 01499a
Also, #0C3689 is too low for C in CMYK color code and too high for M,K

**Comment by Kwoneunhye** [comment]
If I can, I want to show you a color picture !! I want to say that I feel heavy now ;(

**Comment by nayunhwan** [comment]
OK I got it. Thanks your code 👍

**Pull request merged**
