### PR TITLE
Swiss universities

### PR DESCRIPTION
**Pull request by acknowledge**
Here are the different universities of Switzerland. Cheers :)

### CODE REVIEW

**Comment by nayunhwan** [comment]
Oh Thanks your contribution, Can you also write added names of university on the README?

**Comment by acknowledge** [comment]
Oh yes of course !

Are you interested to put links to universities websites on the README file ? I can do it at the same time.

**Comment by nayunhwan** [comment]
Of course!
If you do that, I really thanks your contribution.
Your idea is really awesome! 👍

**Comment by acknowledge** [comment]
Ok great, I'll do it.

Related to your commit : I didn't remove Rochester, I just moved it because it was not right sorted ! So now you have two of them.

**Comment by nayunhwan** [comment]
Oh that's my mistake..
Thanks!!

**Comment by acknowledge** [comment]
No worry. I'll add it to my next commit ;)

**Comment by nayunhwan** [comment]
Really thanks your contribution!!
You are super awesome guy! Thanks!! 👍 👍 👍

**Comment by acknowledge** [comment]
No problem. 
MSP power!

**Pull request merged**
